name: csrldm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=23.2.1
  - cudatoolkit=12.1
  - pytorch=2.1.2
  - torchvision=0.16.2
  - numpy=1.24.3
  - pip:
      - albumentations==0.4.3
      - basicsr==1.4.2
      - einops==0.7.0
      - gradio==4.22.0
      - numpy==1.24.3
      - omegaconf==2.1.1
      - open_clip_torch==2.23.0
      - opencv_python==4.1.2.30
      - opencv_python_headless==4.8.0.76
      - Pillow==9.5.0
      - Pillow==10.2.0
      - pytorch_lightning==1.4.2
      - safetensors==0.4.2
      - scipy==1.9.1
      - timm==0.9.12
      - torch==2.1.2
      - torchvision==0.16.2
      - tqdm==4.66.1
      - transformers==4.36.2
      - ttach==0.0.3
      - xformers==0.0.22.post7